=== one-lab/one/platform/core/persistence/source/src/test/resources/META-INF/dbscript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<dbs:schema targetNamespace="http://www.vmars.org/dbscript"
	elementFormDefault="qualified" xmlns:dbs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.vmars.org/dbscript">
	<dbs:element name="dbscripts">
		<dbs:complexType>
			<dbs:sequence>
				<dbs:element name="typeAlias" minOccurs="0" maxOccurs="unbounded">
					<dbs:complexType>
						<dbs:attribute name="type" use="required">
							<dbs:simpleType>
								<dbs:restriction base="dbs:string">
									<dbs:minLength value="0" />
								</dbs:restriction>
							</dbs:simpleType>
						</dbs:attribute>
						<dbs:attribute name="alias" use="required">
							<dbs:simpleType>
								<dbs:restriction base="dbs:string">
									<dbs:minLength value="0" />
								</dbs:restriction>
							</dbs:simpleType>
						</dbs:attribute>
					</dbs:complexType>
				</dbs:element>

				<dbs:element name="dbscript" minOccurs="0" maxOccurs="unbounded">
					<dbs:complexType mixed="true">
						<dbs:choice  minOccurs="0" maxOccurs="unbounded">
							<dbs:sequence id="conditionSeq">
								<dbs:choice minOccurs="0" maxOccurs="unbounded">
									<dbs:element name="inCondition" minOccurs="0" maxOccurs="unbounded">
										<dbs:complexType mixed="true">
											<dbs:attribute name="property" use="required">
												<dbs:simpleType>
													<dbs:restriction base="dbs:string">
														<dbs:minLength value="0" />
													</dbs:restriction>
												</dbs:simpleType>
											</dbs:attribute>
										</dbs:complexType>
									</dbs:element>
									<dbs:sequence>
										<dbs:element name="ifCondition" minOccurs="0">
											<dbs:complexType>
												<dbs:attribute name="property" use="required">
													<dbs:simpleType>
														<dbs:restriction base="dbs:string">
															<dbs:minLength value="0" />
														</dbs:restriction>
													</dbs:simpleType>
												</dbs:attribute>
												<dbs:attribute name="operator" use="required">
													<dbs:simpleType>
														<dbs:restriction base="dbs:string">
															<dbs:minLength value="0" />
														</dbs:restriction>
													</dbs:simpleType>
												</dbs:attribute>
												<dbs:attribute name="value" use="required">
													<dbs:simpleType>
														<dbs:restriction base="dbs:string">
															<dbs:minLength value="0" />
														</dbs:restriction>
													</dbs:simpleType>
												</dbs:attribute>
											</dbs:complexType>
										</dbs:element>
										<dbs:element name="elseIfCondition" minOccurs="0">
											<dbs:complexType>
												<dbs:attribute name="property" use="required">
													<dbs:simpleType>
														<dbs:restriction base="dbs:string">
															<dbs:minLength value="0" />
														</dbs:restriction>
													</dbs:simpleType>
												</dbs:attribute>
												<dbs:attribute name="operator" use="required">
													<dbs:simpleType>
														<dbs:restriction base="dbs:string">
															<dbs:minLength value="0" />
														</dbs:restriction>
													</dbs:simpleType>
												</dbs:attribute>
												<dbs:attribute name="value" use="required">
													<dbs:simpleType>
														<dbs:restriction base="dbs:string">
															<dbs:minLength value="0" />
														</dbs:restriction>
													</dbs:simpleType>
												</dbs:attribute>
											</dbs:complexType>
										</dbs:element>
									</dbs:sequence>
									<dbs:element name="ifNotNullCondition" minOccurs="0">
										<dbs:complexType mixed="true">
											<dbs:attribute name="property" use="required">
												<dbs:simpleType>
													<dbs:restriction base="dbs:string">
														<dbs:minLength value="0" />
													</dbs:restriction>
												</dbs:simpleType>
											</dbs:attribute>
										</dbs:complexType>
									</dbs:element>
								</dbs:choice>
								<dbs:element name="elseCondition" minOccurs="0">
								</dbs:element>
								<!-- simple condition , used for simply adding the characters under the node. -->
								<dbs:element name="simpleNode" minOccurs="0">									
								</dbs:element>
							</dbs:sequence>
						</dbs:choice>
						<dbs:attribute name="type" use="required">
							<dbs:simpleType>
								<dbs:restriction base="dbs:string">
									<dbs:enumeration value="hql" />
									<dbs:enumeration value="sql" />
								</dbs:restriction>
							</dbs:simpleType>
						</dbs:attribute>
						<dbs:attribute name="id" use="required">
							<dbs:simpleType>
								<dbs:restriction base="dbs:string">
									<dbs:minLength value="0" />
								</dbs:restriction>
							</dbs:simpleType>
						</dbs:attribute>
						<dbs:attribute name="resultClass" type="dbs:string" />
					</dbs:complexType>
				</dbs:element>
			</dbs:sequence>
			<dbs:attribute name="namespace" use="required">
				<dbs:simpleType>
					<dbs:restriction base="dbs:string">
						<dbs:minLength value="0" />
					</dbs:restriction>
				</dbs:simpleType>
			</dbs:attribute>
		</dbs:complexType>
	</dbs:element>
</dbs:schema>

=== one-lab/one/platform/core/persistence/source/src/test/resources/com/sinosoft/one/data/dbscripts/authorization/role.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbscripts namespace="role" xmlns="http://www.vmars.org/dbscript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmars.org/dbscript ../../../../dbscript.xsd ">
	<typeAlias alias="Role" type="com.sinosoft.emergency.model.authorization.Role"/>
	<typeAlias alias="VRolePermission" type="com.sinosoft.emergency.model.authorization.VRolePermission"/>
	<dbscript type="sql" id="selectRolesByOrgnizationId" resultClass="Role">
		SELECT * FROM sys_t_role r WHERE r.state='1' and r.orgnization_id=?
	</dbscript>
	<dbscript type="sql" id="countRolesByOrgnizationId">
		SELECT count(id) as count FROM sys_t_role WHERE state='1' and orgnization_id=?
	</dbscript>
	<dbscript type="sql" id="countRolesByStationId">
		SELECT count(r.id) as count FROM sys_t_role r, sys_t_station_role rsr WHERE r.state='1' and r.id=rsr.role_id and rsr.station_id=?
	</dbscript>
	<dbscript type="sql" id="countRolesByStationIdAndConditions">
		SELECT count(r.id) as count FROM sys_t_role r, sys_t_station_role rsr WHERE r.state='1' and r.id=rsr.role_id and rsr.station_id=?
		<ifNotNullCondition property="name">
			and r.name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="countRolePermissionByRoleId">
		SELECT count(id) as count FROM sys_t_role_permission WHERE role_id=?
	</dbscript>
	<dbscript type="sql" id="countStationRoleByRoleId">
		SELECT count(id) as count FROM sys_t_station_role WHERE role_id=?
	</dbscript>
	<dbscript type="sql" id="countVRolePermissionsByRoleId">
		select count(role_id) as count from sys_v_role_permissions where role_id=?
	</dbscript>
	<dbscript type="sql" id="countVRolePermissionsByRoleIdAndConditions">
		select count(role_id) as count from sys_v_role_permissions where role_id=?
		<ifNotNullCondition property="name">
			and permission_name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="countRolesByConditions">
		SELECT count(id) as count FROM sys_t_role WHERE orgnization_id=? and state='1'
		<ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
		<ifNotNullCondition property="type">
			and type = #type#
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="selectRolesByTypeAndOrgnizationId" resultClass="Role">
		SELECT * FROM sys_t_role WHERE state='1' and (type = ? or orgnization_id=?)
	</dbscript>
	<dbscript type="sql" id="selectRolesByConditions" resultClass="Role">
		SELECT * FROM sys_t_role r WHERE orgnization_id=? and r.state='1'
		<ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
		<ifNotNullCondition property="type">
			and type = #type#
		</ifNotNullCondition>
	</dbscript>
	
	<dbscript type="sql" id="selectRolesWithNotSelected" resultClass="Role">
		select * from sys_t_role t  where orgnization_id=? and t.state='1' and t.id not in( 
			SELECT r.id FROM sys_t_role r, sys_t_station_role rsr WHERE r.id=rsr.role_id and rsr.station_id=?)
	</dbscript>
	<dbscript type="sql" id="selectPublicRolesWithNotSelected" resultClass="Role">
		select * from sys_t_role r where r.type=? and r.state='1' and r.orgnization_id not in(
			select id from sys_t_orgnization o start with o.id=? 
			connect by PRIOR o.parent_id = o.id) and id not in (SELECT r.id FROM sys_t_role r, sys_t_station_role rsr WHERE r.id=rsr.role_id and rsr.station_id=?)
	</dbscript>
	<dbscript type="sql" id="selectRolesByStationId" resultClass="Role">
		SELECT r.* FROM sys_t_role r, sys_t_station_role rsr WHERE r.state='1' and r.id=rsr.role_id and rsr.station_id=?
	</dbscript>
	<dbscript type="sql" id="selectRolesByStationIdAndConditions" resultClass="Role">
		SELECT r.* FROM sys_t_role r, sys_t_station_role rsr WHERE r.state='1' and r.id=rsr.role_id and rsr.station_id=?
		<ifNotNullCondition property="name">
			and r.name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="selectVRolePermissionByRoleId" resultClass="VRolePermission">
		select * from sys_v_role_permissions where role_id=?
	</dbscript>
	<dbscript type="sql" id="selectVRolePermissionByRoleIdAndConditions" resultClass="VRolePermission">
		select * from sys_v_role_permissions where role_id=? 
		<ifNotNullCondition property="name">
			and permission_name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="deleteRoleById">
		DELETE FROM sys_t_role WHERE id=?
	</dbscript>
	<dbscript type="sql" id="deleteRolePermissionById">
		DELETE FROM sys_t_role_permission WHERE role_id=? and permission_id=?
	</dbscript>
</dbscripts>

=== one-lab/one/platform/core/persistence/source/src/test/resources/com/sinosoft/one/data/dbscripts/authorization/orgnization.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbscripts namespace="orgnization" xmlns="http://www.vmars.org/dbscript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmars.org/dbscript ../../../../dbscript.xsd ">
	<typeAlias alias="Orgnization" type="com.sinosoft.emergency.model.authorization.Orgnization"/>
	<typeAlias alias="Station" type="com.sinosoft.emergency.model.authorization.Station"/>
	<dbscript type="sql" id="countOrgnizationByParentId">
		SELECT count(id) as count FROM sys_t_orgnization WHERE state='1' and parent_id=? 
		<inCondition property="ids">
			and id not in #ids#
		</inCondition>
	</dbscript>
	<dbscript type="sql" id="selectOrgnizationsByParentId" resultClass="Orgnization">
		SELECT * FROM sys_t_orgnization WHERE parent_id=? and state='1' order by id desc
	</dbscript>
	<dbscript type="sql" id="selectStationsByOrgnizationId" resultClass="Station">
		SELECT * FROM sys_t_station WHERE orgnization_id=? and state='1'
	</dbscript>
	<dbscript type="sql" id="selectStationsByNameAndOrgId" resultClass="Station">
		SELECT * FROM sys_t_station WHERE orgnization_id=? and state='1'
		<ifNotNullCondition property="name">
		 and name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="deleteOrgnization">
		update sys_t_orgnization set state='0' where id=?
	</dbscript>
	<dbscript type="sql" id="deleteStation">
		update sys_t_station set state='0' where id=?
	</dbscript>
	<dbscript type="sql" id="countStationByOrgnizationId">
		select (SELECT COUNT(id)
          FROM sys_t_station
         WHERE orgnization_id = ?
           and state = '1') + (select count(id)
                                 from sys_t_orgnization
                                where parent_id = ?
                                  and state = '1') as count
  from dual
	</dbscript>
	<dbscript type="sql" id="selectParentOrgnizationById" resultClass="Orgnization">
		select o.id, o.name, o.code, o.type, o.state, o.parent_id, o.description, o.leaf, o.creator_id, o.create_time, o.modifier_id, o.modify_time from sys_t_orgnization o where o.state='1' start with o.id=? 
      	connect by PRIOR o.parent_id = o.id
	</dbscript>
	<dbscript type="sql" id="selectOrgnizationsByUserId" resultClass="Orgnization">
		select distinct o.id, o.name, o.code, o.type, o.state, o.parent_id, o.description, o.leaf, o.creator_id, o.create_time, o.modifier_id, o.modify_time
		 from sys_t_orgnization o, sys_t_user_station us, sys_t_station s where us.station_id=s.id and o.id=s.orgnization_id and us.user_id=? and s.state='1' and o.state='1' order by o.code asc 
	</dbscript>
	<dbscript type="sql" id="selectStationsByUserId" resultClass="Station">
		SELECT s.id, s.name, s.orgnization_id, s.description, s.type, s.state, s.creator_id, s.create_time, s.modifier_id, s.modify_time FROM sys_t_station s, sys_t_user_station us WHERE s.id=us.station_id and us.user_id=? and s.state='1'
	</dbscript>
	<dbscript type="sql" id="selectOrgnizationsByNameAndUserId" resultClass="Orgnization">
		select distinct o.id, o.name, o.code, o.type, o.state, o.parent_id, o.description, o.leaf, o.creator_id, o.create_time, o.modifier_id, o.modify_time
		 from sys_t_orgnization o, sys_t_user_station us, sys_t_station s where us.station_id=s.id and o.id=s.orgnization_id and us.user_id=? and o.state='1' and s.state='1'
		<ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
	</dbscript>
	
	<dbscript type="sql" id="countOrgnizationsByNameAndUserId">
		select count(distinct o.id) as count
		 from sys_t_orgnization o, sys_t_user_station us, sys_t_station s where us.station_id=s.id and o.id=s.orgnization_id and us.user_id=? and o.state='1' and s.state='1'
		 <ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="countStationsByNameAndOrgId">
		SELECT COUNT(id) AS count FROM sys_t_station WHERE orgnization_id=? and state='1'
		<ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
	</dbscript>
	
	<dbscript type="sql" id="selectOrgnizationsByNameAndParentId" resultClass="Orgnization">
		select o.id, o.name, o.code, o.type, o.state, o.parent_id, o.description, o.leaf, o.creator_id, o.create_time, o.modifier_id, o.modify_time
		 from sys_t_orgnization o where o.state='1'
		 <ifNotNullCondition property="parentId">
		 	and o.parent_id=#parentId#
		 </ifNotNullCondition>
		 <elseCondition>
		 	and o.parent_id is null
		 </elseCondition>
		 <ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="countOrgnizationsByNameAndParentId">
		select count(o.id) as count
		 from sys_t_orgnization o where o.state='1'
		 <ifNotNullCondition property="parentId">
		 	and o.parent_id=#parentId#
		 </ifNotNullCondition>
		 <elseCondition>
		 	and o.parent_id is null
		 </elseCondition>
		 <ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="selectOrgnizationCodeByParentId">
		select to_char(max(code)) from sys_t_orgnization where 
		<ifNotNullCondition property="parentId">
			parent_id=#parentId#
		</ifNotNullCondition>
		<elseCondition>
			parent_id is NULL
		</elseCondition>
	</dbscript>
	<dbscript type="sql" id="selectUserStationNamesByUserId" resultClass="String">
		select o.name || '-' || s.name as station_name from sys_t_orgnization o, sys_t_station s, sys_t_user_station us where s.orgnization_id=o.id and us.station_id=s.id and us.user_id=?
	</dbscript>
	<dbscript type="sql" id="deleteStationRole">
		DELETE FROM sys_t_station_role WHERE station_id=? and role_id=?
	</dbscript>
	<dbscript type="sql" id="deleteStationRoles">
		DELETE FROM sys_t_station_role WHERE 1!=1 
		<inCondition property="stationIds">
			or station_id in #stationIds#
		</inCondition>
	</dbscript>
	<dbscript type="sql" id="selectOrgnizationByCodes" resultClass="Orgnization">
		select * from sys_t_orgnization t where state='1'
		<inCondition property="codes">
			and t.code in #codes#
		</inCondition>
	</dbscript>
</dbscripts>

=== one-lab/one/platform/core/persistence/source/src/test/resources/com/sinosoft/one/data/dbscripts/authorization/permission.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbscripts namespace="permission" xmlns="http://www.vmars.org/dbscript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmars.org/dbscript ../../../../dbscript.xsd ">
	<typeAlias alias="Permission" type="com.sinosoft.emergency.model.authorization.Permission"/>
	<typeAlias alias="VUserPermission" type="com.sinosoft.emergency.model.authorization.VUserPermission"/>
	<dbscript type="sql" id="selectPermissionsByModuleId" resultClass="Permission">
		SELECT * FROM sys_t_permission WHERE state='1' and module_id=?
	</dbscript>
	<dbscript type="sql" id="selectPermissionsByConditions" resultClass="Permission">
		SELECT * FROM sys_t_permission WHERE state='1'
		<ifNotNullCondition property="moduleId">
			and module_id = #moduleId#
		</ifNotNullCondition>
		<elseCondition>
			and module_id is null
		</elseCondition>
		<ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="selectVUserPermissionsByUserIdAndRoleId" resultClass="VUserPermission">
		select * from sys_v_user_permission up 
		where up.user_id=? 
		<ifNotNullCondition property="moduleId">
		and module_id=#moduleId#
		</ifNotNullCondition>
		<elseCondition>
		and module_id is null
		</elseCondition>
		<simpleNode>
		and up.id not in (select t.permission_id from sys_v_role_permissions t where t.role_id=?)
		</simpleNode>
	</dbscript>
	<dbscript type="sql" id="selectVUserPermissionsByUserId" resultClass="VUserPermission">
		select * from sys_v_user_permission up 
		where up.user_id=? 
	</dbscript>
	
	<dbscript type="sql" id="countPermissionsByModuleId">
		SELECT count(id) as count FROM sys_t_permission WHERE state='1' and module_id=?
	</dbscript>
	<dbscript type="sql" id="countPermissionsByPermissionId">
		SELECT count(id) as count FROM sys_t_role_permission WHERE permission_id=?
	</dbscript>
	<dbscript type="sql" id="countPermissionsByConditions">
		SELECT count(id) as count FROM sys_t_permission WHERE state='1'
		<ifNotNullCondition property="moduleId">
			and module_id = #moduleId#
		</ifNotNullCondition>
		<elseCondition>
			and module_id is null
		</elseCondition>
		<ifNotNullCondition property="name">
			and name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="deletePermissionById">
		DELETE FROM sys_t_permission WHERE id=?
	</dbscript>
</dbscripts>

=== one-lab/one/platform/core/persistence/source/src/test/resources/com/sinosoft/one/data/dbscripts/authorization/infoTransfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbscripts namespace="infoTransfer" xmlns="http://www.vmars.org/dbscript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmars.org/dbscript ../../../../../../../../bin/src/main/resources/dbscript.xsd ">
<typeAlias alias="bmjbxxModel_auth" type="com.sinosoft.emergency.model.authorization.Bmjbxx"/>
<typeAlias alias="orgnizationModel" type="com.sinosoft.emergency.model.authorization.Orgnization"/>
<typeAlias alias="employeeModel" type=" com.sinosoft.emergency.model.authorization.Employee"/>
<dbscript type="sql" id="isLeafBmjbxx">
	select count(id) as count from t_bs_gy_bmjbxx where parent_id=?
</dbscript>
<dbscript type="hql"  id="selectBmjbxx" resultClass="bmjbxxModel_auth">
	select new com.sinosoft.emergency.model.authorization.Bmjbxx(id,mc) from com.sinosoft.emergency.model.authorization.Bmjbxx a where a.parent_id in (?)
</dbscript>
<dbscript type="sql" id="selectOrgnization" resultClass="orgnizationModel">
	select * from sys_t_orgnization where 1=1
	<ifNotNullCondition property="key">
		and parent_id in (#key#)
	</ifNotNullCondition>
	<elseCondition>
		and parent_id is NULL
	</elseCondition>
</dbscript>
<dbscript type="hql" id="selectEmployee" resultClass="employeeModel">
	select new Employee(ID,ID_BMJBXX,XB,MC,MZ,SFZH,CS_RQ,CJGZ_RQ,JRXT_RQ,YGZT_BZ,SFHR_BZ,CSZY,YGXZ_DM,BG_DZ) from Employee a where a.ID_BMJBXX=?
</dbscript>
<dbscript type="sql" id="selectEmployeeNum">
	select count(id) as count from t_bs_gy_ryjbxx t where t.id_bmjbxx=?
</dbscript>
</dbscripts>

=== one-lab/one/platform/core/persistence/source/src/test/resources/com/sinosoft/one/data/dbscripts/authorization/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbscripts namespace="user" xmlns="http://www.vmars.org/dbscript"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.vmars.org/dbscript ../../../../dbscript.xsd ">
	<typeAlias alias="User" type="com.sinosoft.emergency.model.authorization.User"/>
	<typeAlias alias="EmDeptUser" type="com.sinosoft.emergency.model.emdeptmanage.EmDeptUser"/>
	<dbscript type="sql" id="selectUserByUsername" resultClass="User">
		SELECT * FROM sys_t_user WHERE (username=? or hr_id=?) and state='1' 
	</dbscript>
	<dbscript type="sql" id="countUsersByUsername">
		SELECT count(t.id) as count FROM sys_t_user t where t.username=?
	</dbscript>
	<dbscript type="sql" id="countUsersByStationId">
		SELECT count(u.id) as count FROM sys_t_user_station us, sys_t_user u WHERE us.user_id=u.id and station_id=? and u.state='1' 
	</dbscript>
	<dbscript type="sql" id="selectUsersByStationId" resultClass="User">
		SELECT * FROM sys_t_user WHERE station_id=?  and state='1'
	</dbscript>
	<dbscript type="sql" id="selectUsersByOrgnizationId" resultClass="User">
		SELECT * FROM sys_t_user WHERE orgnization_id=?  and state='1'
	</dbscript>
	<dbscript type="sql" id="selectUsersByConditions" resultClass="User">
		SELECT distinct u.id, u.username, u.password, u.name, u.gender, u.birthday, u.email, u.telephone, u.orgnization_id, u.state, u.creator_id, u.create_time, u.modifier_id, u.modify_time,u.hr_id, u.is_handle_contacter FROM sys_t_user u WHERE u.orgnization_id=?  and u.state='1'
		<ifNotNullCondition property="username">
			and u.username like %username%
		</ifNotNullCondition>
		<ifNotNullCondition property="name">
			and u.name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="countUsersByOrgnizationId">
		SELECT count(id) as count FROM sys_t_user WHERE orgnization_id=? and state='1' 
	</dbscript>
	<dbscript type="sql" id="countUsersByConditions">
		SELECT count(distinct u.id) as count FROM sys_t_user u WHERE u.orgnization_id=?  and u.state='1'
		<ifNotNullCondition property="username">
			and u.username like %username%
		</ifNotNullCondition>
		<ifNotNullCondition property="name">
			and u.name like %name%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="selectUsersByEmDeptId" resultClass="User">
		SELECT * FROM sys_t_user u , t_em_dept_user edu 
			WHERE u.id=edu.user_id
			AND u.state='1'
			AND	edu.em_dept_id=?
	</dbscript>
	<dbscript type="sql" id="deleteUser">
		update sys_t_user set state='0' where id=?
	</dbscript>
	<dbscript type="sql" id="deleteUserStationsByUserId">
		delete from sys_t_user_station where user_id=?
	</dbscript>
	<dbscript type="sql" id="deleteUserStations">
		delete from sys_t_user_station where user_id=?
		<inCondition property="stations">
		and station_id in #stations#
		</inCondition>
	</dbscript>
	<dbscript type="sql" id="deleteEmDeptUsers">
		delete from t_em_dept_user where user_id=?
		<inCondition property="emDeptIds">
		and em_dept_id in #emDeptIds#
		</inCondition> 
	</dbscript>
	<dbscript type="sql" id="selectHRInfoByName">
		select r.id as id, r.mc as name, b.mc_j as deptName,z.mc as positionName, r.xb as gender, to_char(r.cs_rq, 'yyyy-mm-dd') as birthday from t_bs_gy_ryjbxx r, t_bs_gy_bmjbxx b,T_BS_DM_ZW z where r.id_bmjbxx=b.id(+) and r.zw_dm=z.id(+) and r.mc=? and r.jl_zt='Y' and b.jl_zt='Y' order by r.id
	</dbscript>
	<dbscript type="sql" id="resetPassword">
		update sys_t_user t set t.password = ?, t.modify_time=to_date(?, 'yyyy-mm-dd HH24:MI:ss'), t.modifier_id=?
		<inCondition property="ids">
		where t.id in #ids#
		</inCondition>
	</dbscript>
	<dbscript type="sql" id="selectEmDeptUsersByUserId" resultClass="EmDeptUser">
		select * from t_em_dept_user t where t.user_id=?
	</dbscript>
</dbscripts>

=== one-lab/one/platform/core/persistence/source/src/test/resources/com/sinosoft/one/data/dbscripts/authorization/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<dbscripts namespace="module" xmlns="http://www.vmars.org/dbscript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmars.org/dbscript ../../../../dbscript.xsd ">
	<typeAlias alias="Module" type="com.sinosoft.emergency.model.authorization.Module"/>
	<dbscript type="sql" id="selectModulesByUserid" resultClass="Module">
		SELECT id, name, code, description, url, parent_id, leaf,creator_id, create_time, modifier_id, modify_time, state, sort FROM sys_v_user_module um 
		WHERE um.user_id=?
		<ifNotNullCondition property="parentId">
			and um.parent_id=#parentId# order by sort asc
		</ifNotNullCondition>
		<elseCondition>
			and um.parent_id is NULL order by sort asc
		</elseCondition>
	</dbscript>
	<dbscript type="sql" id="countModulesByUserIdAndParentId">
		SELECT count(um.id) as count FROM sys_v_user_module um 
		WHERE um.user_id=? 
		<ifNotNullCondition property="parentId">
			and um.parent_id=#parentId#
		</ifNotNullCondition>
		<elseCondition>
			and um.parent_id is NULL
		</elseCondition>
	</dbscript>
	<dbscript type="sql" id="selectModulesByNameAndUrl" resultClass="Module">
		SELECT id, name, code, description, url, parent_id, leaf,creator_id, create_time, modifier_id, modify_time, state, sort FROM sys_t_module um 
		WHERE um.state='1'
		<ifNotNullCondition property="parentId">
			and um.parent_id=#parentId# 
		</ifNotNullCondition>
		<elseCondition>
			and um.parent_id is NULL
		</elseCondition>
		<ifNotNullCondition property="name">
			and um.name like %name%
		</ifNotNullCondition>
		<ifNotNullCondition property="url">
			and um.url like %url%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="countModulesByNameAndUrl">
		SELECT count(um.id) as count FROM sys_t_module um 
		WHERE um.state='1'
		<ifNotNullCondition property="parentId">
			and um.parent_id=#parentId#
		</ifNotNullCondition>
		<elseCondition>
			and um.parent_id is NULL
		</elseCondition>
		<ifNotNullCondition property="name">
			and um.name like %name%
		</ifNotNullCondition>
		<ifNotNullCondition property="url">
			and um.url like %url%
		</ifNotNullCondition>
	</dbscript>
	<dbscript type="sql" id="countModulesByParentId">
		SELECT count(id) as count FROM sys_t_module 
		WHERE state='1'
		<ifNotNullCondition property="parentId">
			and parent_id = #parentId#
		</ifNotNullCondition>
		<elseCondition>
			and parent_id is null
		</elseCondition>
	</dbscript>
	<dbscript type="sql" id="countSubModulesByParentId">
		SELECT count(id) as count FROM sys_t_module 
		WHERE parent_id=? and state='1'
		<inCondition property="ids">
			and id not in #ids#
		</inCondition>
	</dbscript>
	<dbscript type="sql" id="selectModuleCodeByParentId">
		select to_char(max(code)) from sys_t_module where 
		<ifNotNullCondition property="parentId">
			parent_id=#parentId#
		</ifNotNullCondition>
		<elseCondition>
			parent_id is NULL
		</elseCondition>
	</dbscript>
	<dbscript type="sql" id="selectModuleSortByParentId">
		select to_char(max(sort)) from sys_t_module where 
		<ifNotNullCondition property="parentId">
			parent_id=#parentId#
		</ifNotNullCondition>
		<elseCondition>
			parent_id is NULL
		</elseCondition>
	</dbscript>
	<dbscript type="sql" id="selectModulesByIds" resultClass="Module">
		select * from sys_t_module where state='1'
		<inCondition property="moduleIds">
		and id in #moduleIds#
		</inCondition>
		<simpleNode>
		order by sort asc
		</simpleNode>
	</dbscript>
	<dbscript type="sql" id="selectModulesByParentId" resultClass="Module">
		select * from sys_t_module where state='1'
		<ifNotNullCondition property="parentId">
			and parent_id=#parentId#
		</ifNotNullCondition>
		<elseCondition>
			and parent_id is null
		</elseCondition>
		<simpleNode>
			order by sort asc
		</simpleNode>
	</dbscript>
	<dbscript type="sql" id="updateModuleLeaf">
		update sys_t_module set leaf=? where id=?
	</dbscript>
	<dbscript type="sql" id="deleteModule">
		delete from sys_t_module where id =?
	</dbscript>
</dbscripts>
